services:
  mysqldb:
    image: mysql:lts
    container_name: mysqlcontainer
    restart: unless-stopped
    volumes:
      - mysqldb:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT} 
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    restart: unless-stopped
    volumes:
      - /nodeapp:/code
    ports:
      - ${SERVER_PORT}:${SERVER_PORT} 
    expose:
      - ${SERVER_PORT} 
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_DATABASE}
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - mysqldb
    networks:
      - internalnet

volumes:
  mysqldb:
networks:
  internalnet:
    driver: bridge