services:
  mysql_db:
    image: mysql:lts
    container_name: mysql_container
    restart: unless-stopped
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT} 
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: prod
      SERVICE_NAME: mysql_db
    networks:
      - internalnet

  node_app:
    container_name: node_app_container
    build: .
    image: node_app:v1
    restart: unless-stopped
    volumes:
      - /nodeapp:/code
    ports:
      - ${SERVER_PORT}:${SERVER_PORT} 
    expose:
      - ${SERVER_PORT} 
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_DATABASE}
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: node_app_service
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - mysql_db
    networks:
      - internalnet

volumes:
  mysql_db:
networks:
  internalnet:
    driver: bridge