services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - /database:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD} 
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: prod
      SERVICE_NAME: mysql_db-service
    networks:
      - internalnet

  node_app:
    container_name: node_app-container
    build: .
    image: node_app:v1
    volumes:
      - /node_app:/code
    ports: 
      - ${SERVER_PORT}:${SERVER_PORT}
    expose:
      - ${SERVER_PORT}
    environment:
      DB_HOST: mysql_db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_DATABASE}
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: node_app-service
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - mysql_db
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge